import { z } from 'zod';

import { createPalette } from '@/styles/colors';
import { ChatPersistence, ChatPosition } from '@/types';

import { AnyExtension } from './Extension.dto';

const ColorPalette = z.object({
  50: z.string(),
  100: z.string(),
  200: z.string(),
  300: z.string(),
  400: z.string(),
  500: z.string(),
  600: z.string(),
  700: z.string(),
  800: z.string(),
  900: z.string(),
});

export const DEFAULT_AVATAR = 'https://cdn.voiceflow.com/assets/logo.png';

export type AssistantOptions = z.infer<typeof AssistantOptions>;
export type RawAssistantOptions = z.input<typeof AssistantOptions>;

export const LauncherOptions = z
  .object({
    withLabel: z.boolean().default(false),
    label: z.string().optional(),
    image: z.string().default(DEFAULT_AVATAR),
  })
  .default({});

export const BannerOptions = z
  .object({
    showBanner: z.boolean().default(true),
    header: z.string().default('Voiceflow Assistant'),
    description: z.string().default('How can I help you today?'),
    image: z.string().default(DEFAULT_AVATAR),
  })
  .default({});

export const AIDisclaimerOptions = z
  .object({
    showDisclaimer: z.boolean().default(true),
    text: z.string().default('Generated by AI, double check for accuracy'),
  })
  .default({});

export const FooterOptions = z
  .object({
    showVoiceflowLink: z.boolean().default(true),
    showFooterLink: z.boolean().default(true),
    linkText: z.string().default('Privacy'),
    linkUrl: z.string().optional(),
  })
  .default({});

export const DisclaimerOptions = z
  .object({
    showDisclaimer: z.boolean().default(false),
    header: z.string().optional(),
    description: z.string().optional(),
    primaryButtonText: z.string().default('I Agree'),
    secondaryButtonText: z.string().optional(),
    secondaryButtonUrl: z.string().optional(),
  })
  .default({});

export const AssistantOptions = z
  .object({
    // Settings under: Appearance & style
    fontFamily: z.string().default('UCity Pro'),
    palette: z.union([z.string(), ColorPalette]).default(createPalette()),
    image: z.string().default(DEFAULT_AVATAR), // Header image
    agentImage: z.string().default(DEFAULT_AVATAR),

    // Banner image & text
    banner: BannerOptions,

    // Launcher type & image
    launcher: LauncherOptions,

    inputPlaceholder: z.string().default('Message...'),
    aiDisclaimer: AIDisclaimerOptions,

    // Security
    approvedDomains: z.string().optional(),
    agentDisclaimer: DisclaimerOptions,

    title: z.string().default('Voiceflow Assistant'),
    avatar: z.string().default(DEFAULT_AVATAR),
    watermark: z.boolean().default(true), // 'Powered by Voiceflow' footer link
    feedback: z.boolean().default(false),
    stylesheet: z.union([z.string(), z.string().array()]).optional(), // Custom user stylesheets
    persistence: z.nativeEnum(ChatPersistence).default(ChatPersistence.LOCAL_STORAGE),

    // Settings under: Interface & modality
    position: z.nativeEnum(ChatPosition).default(ChatPosition.RIGHT),
    spacing: z
      .object({
        side: z.number().default(30), // px
        bottom: z.number().default(30), // px
      })
      .default({}),
    audioInterface: z.boolean().default(false), // Voice input
    defaultAudioOutput: z.boolean().optional(), // Voice output

    extensions: AnyExtension.array().default([]),
  })
  .default({});
